sudo: false

language: android
jdk: oraclejdk8

env:
 matrix:
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3 ANDROID_API_LEVEL=28
android:
  components:
    - android-$ANDROID_API_LEVEL
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew clean build --stacktrace

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}"

install:
  - echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-${ANDROID_API_LEVEL}"

notifications:
  email: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle